#!/bin/bash

# Generate RSA key pair with 4096 bits
openssl genpkey -algorithm RSA -out school.pem -aes256 -pass pass:betty -pkeyopt rsa_keygen_bits:4096

# Extract public key
openssl rsa -pubout -in school.pem -out school.pub.pem

