#!/bin/bash

# Define key name, number of bits, and passphrase
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Generate the RSA key pair with options
ssh-keygen -t rsa -b $KEY_BITS -f "$KEY_NAME" -C "" -N "$PASSPHRASE"

# Check if key generation was successful
if [ $? -eq 0 ]; then
  echo "RSA key pair created successfully!"
  echo "Private key: $KEY_NAME"
  echo "Public key: $KEY_NAME.pub"
else
  echo "Error creating key pair!"
fi
