#!/bin/bash

# Check if the key pair files already exist
if [[ -e school || -e school.pub ]]; then
    echo "Key pair files already exist. Aborting."
    exit 1
fi

# Create RSA key pair with 4096 bits and passphrase protection
ssh-keygen -t rsa -b 4096 -N "betty" -f school

# Check if key generation was successful
if [ $? -eq 0 ]; then
    echo "RSA key pair created successfully."
else
    echo "Failed to create RSA key pair."
    exit 1
fi

